#ifndef PORTS_H
#define PORTS_H

// === PORTS ===
#define LEFT_MOTOR EV3_PORT_A
#define RIGHT_MOTOR EV3_PORT_D
#define CRANE EV3_PORT_B
#define FINGER EV3_PORT_C

#define LEFT_MOTOR_TYPE LARGE_MOTOR
#define RIGHT_MOTOR_TYPE LARGE_MOTOR
#define CRANE_TYPE LARGE_MOTOR
#define FINGER_TYPE MEDIUM_MOTOR

#define LEFT_MOTOR_FLAG_DIG 0
#define RIGHT_MOTOR_FLAG_DIG 1
#define CRANE_FLAG_DIG 2
#define FINGER_FLAG_DIG 3

#define LEFT_COLOR EV3_PORT_2
#define RIGHT_COLOR EV3_PORT_3
#define GATE_COLOR EV3_PORT_4
#define GYRO EV3_PORT_1

#define LEFT_COLOR_TYPE COLOR_SENSOR
#define RIGHT_COLOR_TYPE COLOR_SENSOR
#define GATE_COLOR_TYPE COLOR_SENSOR
#define GYRO_TYPE GYRO_SENSOR

#define LEFT_COLOR_FLAG_DIG 4
#define RIGHT_COLOR_FLAG_DIG 5
#define GATE_COLOR_FLAG_DIG 6
#define GYRO_FLAG_DIG 7

// ===MACHINE INFORMATION===
#define TIRE_RADIUS 55.0f // 直径。milli meter (float)
#define TIRE_DISTANCE 127.1f // milli meter (float)
#define BLACK_BORDER 15

// === CONTROL CONSTANTS ===
#define P_GAIN 0.3f // float
#define GYRO_GAIN 1.0f

// === GENERAL ===
#define PI 3.14f // float

#endif /* PORTS_H */
